feat(order): implement remaining endpoints
FIAP-3SOAT-G15/tech-challenge pull request #37
Opened 2023-10-28 08:20 UTC by giovannidiluca

2023-10-28 08:44 UTC, wellyfrs commented on Fase-1/API/self-order-management/src/main/kotlin/com/fiap/selfordermanagement/adapters/driver/web/api/OrdersAPI.kt
> +    @GetMapping("/{document}")
Esse mapping é o mesmo que o do primeiro do ponto de vista do Spring, vc precisa especificar um path diferente.

Como é uma REST API, existe uma convenção:

- os `resources` precisam estar no path: `/customers`, `/orders`, etc (sempre no plural quando fizer sentido)
- IDs procedem resources: `/customers/{id}`, `/orders/{id}` (sem ID retorna todos, com ID retorna único)
- para filtrar resources, use params: `/orders/status/{status}?userDocument=44455566677`

2023-10-28 08:47 UTC, wellyfrs commented on Fase-1/API/self-order-management/src/main/kotlin/com/fiap/selfordermanagement/adapters/driver/web/api/OrdersAPI.kt
> +    @GetMapping("/{document}")
Talvez um único endpoint `/orders/status/{status}` com params para:

- customerNickname
- customerDocument

Ou ainda, para clientes cadastrados:

- `/customers/{document}/orders/status/{status}`

2023-10-28 12:00 UTC, lucasgabrielsantos approved these changes

2023-10-28 12:25 UTC, wellyfrs requested changes
Por favor, verifique meu comentário 🙏

2023-10-28 21:53 UTC, giovannidiluca commented on Fase-1/API/self-order-management/src/main/kotlin/com/fiap/selfordermanagement/adapters/driver/web/OrderController.kt
> +    }
@wellyfrs acha que faz sentido manter assim? manter toda a lógica em um só endpoint me pareceu mais confuso de compreender o método

2023-10-29 09:34 UTC, wellyfrs commented on Fase-1/API/self-order-management/src/main/kotlin/com/fiap/selfordermanagement/adapters/driver/web/OrderController.kt
> +    }
Ficou top 🚀

2023-10-29 09:35 UTC, wellyfrs approved these changes

2023-10-29 09:35 UTC, merged